### ISSUE TITLE
`cli_args' value in the helm chart was not applied correctly.

### ISSUE THREAD

**Issue by shortstories** [freshworks-oss/redis-operator#19]
## Expected behaviour

```yaml
# values.yaml
image:
  repository: public.n3r.reg.navercorp.com/n3r/freshworks/redis-operator
  pullPolicy: IfNotPresent
  tag: v1.3.0-rc0-f777e5f2
  cli_args:
  - "--concurrency=8"
  - "--k8s-cli-qps-limit=100"
  - "--k8s-cli-burstable-limit=500"
```

```yaml
# Deployments
    spec:
      containers:
      - name: redis-operator
        image: "public.n3r.reg.navercorp.com/n3r/freshworks/redis-operator:v1.3.0-rc0-f777e5f2"
        args:
        - --concurrency=8
        - --k8s-cli-qps-limit=100
        - --k8s-cli-burstable-limit=500
```

## Actual behaviour

```yaml
# Deployments
    spec:
      containers:
      - name: redis-operator
        image: "public.n3r.reg.navercorp.com/n3r/freshworks/redis-operator:v1.3.0-rc0-f777e5f2"
        args:
        - "[--concurrency=8 --k8s-cli-qps-limit=100 --k8s-cli-burstable-limit=500]"
```

---

We should use the `toYaml` function to template it.
